<?php

namespace Razam\Coordinadora\Model\Config\Source;

class States implements \Magento\Framework\Data\OptionSourceInterface
{
    /**
     * @inheridoc
     */
    public function toOptionArray(): array
    {
        return [
                ['label' => 'AIPE','value' => '41016'],
                ['label' => 'ALCALA','value' => '76020'],
                ['label' => 'ALTAMIRA','value' => '41026'],
                ['label' => 'AMAIME','value' => '76520'],
                ['label' => 'ANDALUCIA','value' => '76036'],
                ['label' => 'ANSERMA','value' => '17042'],
                ['label' => 'ANSERMA NUEVO','value' => '76041'],
                ['label' => 'APARTADO','value' => '05045'],
                ['label' => 'ARMENIA','value' => '63001'],
                ['label' => 'BARBOSA','value' => '05079'],
                ['label' => 'BARRANCABERMEJA','value' => '68081'],
                ['label' => 'BARRANQUILLA','value' => '08001'],
                ['label' => 'BAYUNCA','value' => '13001'],
                ['label' => 'BELENCITO','value' => '15491'],
                ['label' => 'BELLO','value' => '05088'],
                ['label' => 'BOGOTA','value' => '11001'],
                ['label' => 'BOSCONIA','value' => '20060'],
                ['label' => 'BRICEÑO','value' => '25758'],
                ['label' => 'BUCARAMANGA','value' => '68001'],
                ['label' => 'BUENAVENTURA','value' => '76109'],
                ['label' => 'BUENOS AIRES','value' => '73001'],
                ['label' => 'BUGA','value' => '76111'],
                ['label' => 'BUGA LA GRANDE','value' => '76113'],
                ['label' => 'CAICEDONIA','value' => '76122'],
                ['label' => 'CAJICA','value' => '25126'],
                ['label' => 'CALARCA','value' => '63130'],
                ['label' => 'CALDAS','value' => '05129'],
                ['label' => 'CALI','value' => '76001'],
                ['label' => 'CALOTO','value' => '19142'],
                ['label' => 'CANDELARIA','value' => '76130'],
                ['label' => 'CAREPA','value' => '05147'],
                ['label' => 'CARTAGENA','value' => '13001'],
                ['label' => 'CARTAGO','value' => '76147'],
                ['label' => 'CATAMBUCO','value' => '52001'],
                ['label' => 'CAUCASIA','value' => '05154'],
                ['label' => 'CERETE','value' => '23162'],
                ['label' => 'CHACHAGUI','value' => '52240'],
                ['label' => 'CHIA','value' => '25175'],
                ['label' => 'CHICORAL','value' => '73268'],
                ['label' => 'CHIGORODO','value' => '05172'],
                ['label' => 'CHINAUTA','value' => '25290'],
                ['label' => 'CHINCHINA','value' => '17174'],
                ['label' => 'CHINU','value' => '23182'],
                ['label' => 'CHIQUINQUIRA','value' => '15176'],
                ['label' => 'CIENAGA','value' => '47189'],
                ['label' => 'CIENAGA DE ORO','value' => '23189'],
                ['label' => 'CIRCASIA','value' => '63190'],
                ['label' => 'COPACABANA','value' => '05212'],
                ['label' => 'COROZAL','value' => '70215'],
                ['label' => 'COTA','value' => '25214'],
                ['label' => 'COVEÑAS','value' => '70221'],
                ['label' => 'CUCUTA','value' => '54001'],
                ['label' => 'DAGUA','value' => '76233'],
                ['label' => 'DOSQUEBRADAS','value' => '66170'],
                ['label' => 'DUITAMA','value' => '15238'],
                ['label' => 'EL CARMELO','value' => '76130'],
                ['label' => 'EL CARMEN DE BOLIVAR','value' => '13244'],
                ['label' => 'EL CARMEN DE VIBORAL','value' => '05148'],
                ['label' => 'EL CENTRO','value' => '68081'],
                ['label' => 'EL CERRITO','value' => '76248'],
                ['label' => 'EL PLACER','value' => '76248'],
                ['label' => 'EL ROSAL','value' => '25260'],
                ['label' => 'EL SANTUARIO','value' => '05697'],
                ['label' => 'EL ZULIA','value' => '54261'],
                ['label' => 'ENVIGADO','value' => '05266'],
                ['label' => 'ESPINAL','value' => '73268'],
                ['label' => 'FACATATIVA','value' => '25269'],
                ['label' => 'FLANDES','value' => '73275'],
                ['label' => 'FLORENCIA','value' => '18001'],
                ['label' => 'FLORIDA','value' => '76275'],
                ['label' => 'FLORIDABLANCA','value' => '68276'],
                ['label' => 'FUNZA','value' => '25286'],
                ['label' => 'FUSAGASUGA','value' => '25290'],
                ['label' => 'GACHANCIPA','value' => '25295'],
                ['label' => 'GAIRA','value' => '47001'],
                ['label' => 'GALAPA','value' => '08296'],
                ['label' => 'GARZON','value' => '41298'],
                ['label' => 'GIGANTE','value' => '41306'],
                ['label' => 'GINEBRA','value' => '76306'],
                ['label' => 'GIRARDOT','value' => '25307'],
                ['label' => 'GIRARDOTA','value' => '05308'],
                ['label' => 'GIRON','value' => '68307'],
                ['label' => 'GUACARI','value' => '76318'],
                ['label' => 'GUALANDAY','value' => '73200'],
                ['label' => 'GUARNE','value' => '05318'],
                ['label' => 'HOBO','value' => '41349'],
                ['label' => 'IBAGUE','value' => '73001'],
                ['label' => 'IPIALES','value' => '52356'],
                ['label' => 'ITAGUI','value' => '05360'],
                ['label' => 'JAMUNDI','value' => '76364'],
                ['label' => 'LA BOQUILLA','value' => '13001'],
                ['label' => 'LA CALERA','value' => '25377'],
                ['label' => 'LA CEJA','value' => '05376'],
                ['label' => 'LA ESTRELLA','value' => '05380'],
                ['label' => 'LA PAILA','value' => '76895'],
                ['label' => 'LA TEBAIDA','value' => '63401'],
                ['label' => 'LA UNION','value' => '76400'],
                ['label' => 'LA URIBE','value' => '76113'],
                ['label' => 'LA VICTORIA','value' => '76403'],
                ['label' => 'LA VIRGINIA','value' => '66400'],
                ['label' => 'LEBRIJA','value' => '68406'],
                ['label' => 'LOBO GUERRERO','value' => '76233'],
                ['label' => 'LORICA','value' => '23417'],
                ['label' => 'LOS PATIOS','value' => '54405'],
                ['label' => 'MADRID','value' => '25430'],
                ['label' => 'MAGANGUE','value' => '13430'],
                ['label' => 'MALAMBO','value' => '08433'],
                ['label' => 'MANIZALES','value' => '17001'],
                ['label' => 'MARINILLA','value' => '05440'],
                ['label' => 'MEDELLIN','value' => '05001'],
                ['label' => 'MELGAR','value' => '73449'],
                ['label' => 'MIRANDA','value' => '19455'],
                ['label' => 'MONDOMO','value' => '19698'],
                ['label' => 'MONTELIBANO','value' => '23466'],
                ['label' => 'MONTENEGRO','value' => '63470'],
                ['label' => 'MONTERIA','value' => '23001'],
                ['label' => 'MORROA','value' => '70473'],
                ['label' => 'MOSQUERA','value' => '25473'],
                ['label' => 'NEIVA','value' => '41001'],
                ['label' => 'NOBSA','value' => '15491'],
                ['label' => 'OBANDO','value' => '76497'],
                ['label' => 'PAIPA','value' => '15516'],
                ['label' => 'PALERMO','value' => '47745'],
                ['label' => 'PALMIRA','value' => '76520'],
                ['label' => 'PAMPLONA','value' => '54518'],
                ['label' => 'PASTO','value' => '52001'],
                ['label' => 'PEREIRA','value' => '66001'],
                ['label' => 'PIEDECUESTA','value' => '68547'],
                ['label' => 'PIENDAMO','value' => '19548'],
                ['label' => 'PITALITO','value' => '41551'],
                ['label' => 'PLANETA RICA','value' => '23555'],
                ['label' => 'PLATO','value' => '47555'],
                ['label' => 'POPAYAN','value' => '19001'],
                ['label' => 'PRADERA','value' => '76563'],
                ['label' => 'PUERTO TEJADA','value' => '19573'],
                ['label' => 'QUIMBAYA','value' => '63594'],
                ['label' => 'RETIRO','value' => '05607'],
                ['label' => 'RICAURTE','value' => '25612'],
                ['label' => 'RIOHACHA','value' => '44001'],
                ['label' => 'RIONEGRO','value' => '05615'],
                ['label' => 'RIOSUCIO','value' => '17614'],
                ['label' => 'ROLDANILLO','value' => '76622'],
                ['label' => 'ROZO','value' => '76520'],
                ['label' => 'SABANETA','value' => '05631'],
                ['label' => 'SAHAGUN','value' => '23660'],
                ['label' => 'SAMPUES','value' => '70670'],
                ['label' => 'SAN ANTONIO DE PRADO','value' => '05001'],
                ['label' => 'SAN JACINTO','value' => '13654'],
                ['label' => 'SAN JUAN NEPOMUCENO','value' => '13657'],
                ['label' => 'SAN PEDRO','value' => '70717'],
                ['label' => 'SAN PEDRO','value' => '76403'],
                ['label' => 'SANTA MARTA','value' => '47001'],
                ['label' => 'SANTA ROSA DE CABAL','value' => '66682'],
                ['label' => 'SANTANDER DE QUILICHAO','value' => '19698'],
                ['label' => 'SEVILLA','value' => '76736'],
                ['label' => 'SIBATE','value' => '25740'],
                ['label' => 'SINCE','value' => '70742'],
                ['label' => 'SINCELEJO','value' => '70001'],
                ['label' => 'SOACHA','value' => '25754'],
                ['label' => 'SOGAMOSO','value' => '15759'],
                ['label' => 'SOLEDAD','value' => '08758'],
                ['label' => 'SONSO','value' => '76318'],
                ['label' => 'SOPO','value' => '25758'],
                ['label' => 'TABIO','value' => '25785'],
                ['label' => 'TAGANGA','value' => '47001'],
                ['label' => 'TENJO','value' => '25799'],
                ['label' => 'TIBASOSA','value' => '15806'],
                ['label' => 'TOCANCIPA','value' => '25817'],
                ['label' => 'TOLU','value' => '70820'],
                ['label' => 'TOLU VIEJO','value' => '70823'],
                ['label' => 'TORO','value' => '76823'],
                ['label' => 'TULUA','value' => '76834'],
                ['label' => 'TUMACO','value' => '52835'],
                ['label' => 'TUNJA','value' => '15001'],
                ['label' => 'TURBACO','value' => '13836'],
                ['label' => 'TURBO','value' => '05837'],
                ['label' => 'UBATE','value' => '25843'],
                ['label' => 'VALLEDUPAR','value' => '20001'],
                ['label' => 'VIJES','value' => '76869'],
                ['label' => 'VILLA DEL ROSARIO','value' => '54874'],
                ['label' => 'VILLA GORGONA','value' => '76130'],
                ['label' => 'VILLA RICA','value' => '19845'],
                ['label' => 'VILLAMARIA','value' => '17873'],
                ['label' => 'VILLAVICENCIO','value' => '50001'],
                ['label' => 'VITERBO','value' => '17877'],
                ['label' => 'YOPAL','value' => '85001'],
                ['label' => 'YOTOCO','value' => '76890'],
                ['label' => 'YUMBO','value' => '76892'],
                ['label' => 'ZARZAL','value' => '76895'],
                ['label' => 'ZIPAQUIRA','value' => '25899']
        ];
    }
}
